import "dotenv/config";
import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { foods as foodsTable } from "./schema";

const staticFoods = [
  { grupo: "Hidratos", alimento: "Papa (cruda o cocida)", cantidadBase: 150, unidad: "g" },
  { grupo: "Hidratos", alimento: "Batata mameya", cantidadBase: 120, unidad: "g" },
  { grupo: "Hidratos", alimento: "Yuca", cantidadBase: 60, unidad: "g" },
  { grupo: "Hidratos", alimento: "Arroz, pasta, couscous o quinoa", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Vasito de arroz o quinoa (medio de 125g)", cantidadBase: 63, unidad: "g" },
  { grupo: "Hidratos", alimento: "Harinas (excepto de almendra)", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Avena o crema de arroz", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Cereales (corn flakes, muesli, copos...)", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Maíz para palomitas", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Pan (molde, tostado, con o sin semillas...)", cantidadBase: 1, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Gnocchi", cantidadBase: 60, unidad: "g" },
  { grupo: "Hidratos", alimento: "Rice cakes dulces", cantidadBase: 2, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Rice cakes salados", cantidadBase: 3, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Plantilla integral", cantidadBase: 1, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Tortillas tipo wrap grandes (1/2 ud)", cantidadBase: 40, unidad: "g" },
  { grupo: "Hidratos", alimento: "Base para pizza (1/4 de base)", cantidadBase: 35, unidad: "g" },
  { grupo: "Hidratos", alimento: "Azúcar, dextrosa, amilopectina...", cantidadBase: 25, unidad: "g" },
  { grupo: "Hidratos", alimento: "Mermelada (la que sea)", cantidadBase: 40, unidad: "g" },
  { grupo: "Hidratos", alimento: "Miel", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Frutas deshidratadas (pasas, ciruelas...)", cantidadBase: 30, unidad: "g" },
  { grupo: "Hidratos", alimento: "Dátiles", cantidadBase: 35, unidad: "g" },
  { grupo: "Hidratos", alimento: "Castañas ya peladas", cantidadBase: 50, unidad: "g" },
  { grupo: "Hidratos", alimento: "Melón o sandía", cantidadBase: 300, unidad: "g" },
  { grupo: "Hidratos", alimento: "Paraguayo o melocotón", cantidadBase: 230, unidad: "g" },
  { grupo: "Hidratos", alimento: "Berries (frescos o congelados)", cantidadBase: 200, unidad: "g" },
  { grupo: "Hidratos", alimento: "Ciruela", cantidadBase: 200, unidad: "g" },
  { grupo: "Hidratos", alimento: "Piña en su jugo", cantidadBase: 200, unidad: "g" },
  { grupo: "Hidratos", alimento: "Uvas", cantidadBase: 150, unidad: "g" },
  { grupo: "Hidratos", alimento: "Caquis", cantidadBase: 150, unidad: "g" },
  { grupo: "Hidratos", alimento: "Guineo (uno pequeño)", cantidadBase: 100, unidad: "g" },
  { grupo: "Hidratos", alimento: "Manzana o pera", cantidadBase: 1, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Mandarinas o kiwis", cantidadBase: 2, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Guisantes frescos o en lata", cantidadBase: 130, unidad: "g" },
  { grupo: "Hidratos", alimento: "Maíz en lata", cantidadBase: 130, unidad: "g" },
  { grupo: "Hidratos", alimento: "Judía verde, alcachofa, menestra...", cantidadBase: 400, unidad: "g" },
  { grupo: "Hidratos", alimento: "Pimientos en pote", cantidadBase: 300, unidad: "g" },
  { grupo: "Hidratos", alimento: "Yogurt natural azucarado (1 yogurt)", cantidadBase: 125, unidad: "g" },
  { grupo: "Hidratos", alimento: "Bebida de arroz, avena, arroz y coco...", cantidadBase: 240, unidad: "ml" },
  { grupo: "Hidratos", alimento: "Bebida de arroz sin azúcar Hacendado", cantidadBase: 250, unidad: "ml" },
  { grupo: "Hidratos", alimento: "Bebida de avena sin azúcar", cantidadBase: 600, unidad: "ml" },
  { grupo: "Hidratos", alimento: "Bebida de soja chocolate NO Hacendado", cantidadBase: 140, unidad: "ml" },
  { grupo: "Hidratos", alimento: "Melocotón", cantidadBase: 1, unidad: "ud" },
  { grupo: "Hidratos", alimento: "Jugo comercial", cantidadBase: 200, unidad: "ml" },
  { grupo: "Hidratos", alimento: "Jugo comercial sin azúcares añadidos", cantidadBase: 500, unidad: "ml" },
  { grupo: "Proteína", alimento: "Proteína en polvo (whey, iso, vegetal, caseína)", cantidadBase: 30, unidad: "g" },
  { grupo: "Proteína", alimento: "Pescado blanco (Tilapia, bacalao, lubina...)", cantidadBase: 120, unidad: "g" },
  { grupo: "Proteína", alimento: "Mariscos (pulpo, calamar, sepia...)", cantidadBase: 120, unidad: "g" },
  { grupo: "Proteína", alimento: "Camarones", cantidadBase: 120, unidad: "g" },
  { grupo: "Proteína", alimento: "Atún en agua (1 lata)", cantidadBase: 120, unidad: "g" },
  { grupo: "Proteína", alimento: "Atún en aceite", cantidadBase: 50, unidad: "g" },
  { grupo: "Proteína", alimento: "Carne blanca sin piel (pollo, pavo...)", cantidadBase: 100, unidad: "g" },
  { grupo: "Proteína", alimento: "Carne roja magra (sin grasa)", cantidadBase: 80, unidad: "g" },
  { grupo: "Proteína", alimento: "Hígado", cantidadBase: 80, unidad: "g" },
  { grupo: "Proteína", alimento: "Lomo embuchado", cantidadBase: 50, unidad: "g" },
  { grupo: "Proteína", alimento: "Soja texturizada", cantidadBase: 30, unidad: "g" },
  { grupo: "Proteína", alimento: "Claras de huevo (6-7 claras)", cantidadBase: 200, unidad: "ml" },
  { grupo: "Proteína", alimento: "Seitán", cantidadBase: 80, unidad: "g" },
  { grupo: "Proteína", alimento: "Queso fresco batido 0%", cantidadBase: 220, unidad: "g" },
  { grupo: "Proteína", alimento: "Queso fresco tipo Burgos (2 tarrinas pequeñas)", cantidadBase: 150, unidad: "g" },
  { grupo: "Proteína", alimento: "Requesón 0%", cantidadBase: 140, unidad: "g" },
  { grupo: "Proteína", alimento: "Queso cottage light", cantidadBase: 120, unidad: "g" },
  { grupo: "Proteína", alimento: "Yogurt YoPro Danone (no choco)", cantidadBase: 1, unidad: "ud" },
  { grupo: "Proteína", alimento: "Yogurt +proteínas (no choco no vainilla)", cantidadBase: 180, unidad: "g" },
  { grupo: "Grasas", alimento: "Aceite vegetal (Oliva, canola, maíz, sesamo...)", cantidadBase: 10, unidad: "ml" },
  { grupo: "Grasas", alimento: "Aceitunas (verdes, negras o rellenas)", cantidadBase: 60, unidad: "g" },
  { grupo: "Grasas", alimento: "Aguacate o guacamole", cantidadBase: 60, unidad: "g" },
  { grupo: "Grasas", alimento: "Semillas (girasol, lino, calabaza, chía)", cantidadBase: 18, unidad: "g" },
  { grupo: "Grasas", alimento: "Nueces", cantidadBase: 15, unidad: "g" },
  { grupo: "Grasas", alimento: "Mantequilla de nueces (maní, almendra...)", cantidadBase: 15, unidad: "g" },
  { grupo: "Grasas", alimento: "Harina de almendra", cantidadBase: 15, unidad: "g" },
  { grupo: "Grasas", alimento: "Coco rallado (o harina)", cantidadBase: 15, unidad: "g" },
  { grupo: "Grasas", alimento: "Coco natural", cantidadBase: 30, unidad: "g" },
  { grupo: "Grasas", alimento: "Cacao puro desgrasado en polvo", cantidadBase: 30, unidad: "g" },
  { grupo: "Grasas", alimento: "Chocolate +72% (2 onzas)", cantidadBase: 20, unidad: "g" },
  { grupo: "Grasas", alimento: "Mantequilla", cantidadBase: 15, unidad: "g" },
  { grupo: "Grasas", alimento: "Mantequilla light", cantidadBase: 25, unidad: "g" },
  { grupo: "Grasas", alimento: "Margarina", cantidadBase: 20, unidad: "g" },
  { grupo: "Grasas", alimento: "Margarina light", cantidadBase: 30, unidad: "g" },
  { grupo: "Grasas", alimento: "Heavy cream", cantidadBase: 50, unidad: "g" },
  { grupo: "Grasas", alimento: "Nata para montar", cantidadBase: 30, unidad: "g" },
  { grupo: "Grasas", alimento: "Mayonesa", cantidadBase: 15, unidad: "g" },
  { grupo: "Grasas", alimento: "Mayonesa light", cantidadBase: 30, unidad: "g" },
  { grupo: "Grasas", alimento: "Gazpacho", cantidadBase: 200, unidad: "ml" },
  { grupo: "Grasas", alimento: "Tomate frito receta artesana Hacendado", cantidadBase: 50, unidad: "g" },
  { grupo: "Grasas", alimento: "Tomate frito comercial", cantidadBase: 130, unidad: "g" },
  { grupo: "Grasas", alimento: "Tomate frito estilo casero", cantidadBase: 100, unidad: "g" },
  { grupo: "Grasas", alimento: "Yogurt griego natural", cantidadBase: 80, unidad: "g" },
  { grupo: "Grasas", alimento: "Bebida de almendras sin azúcar", cantidadBase: 600, unidad: "ml" },
  { grupo: "Grasas", alimento: "Bebida de almendras Eco-Cesta", cantidadBase: 400, unidad: "ml" },
  { grupo: "Grasas", alimento: "Bebida de almendras Alpro o Hacendado", cantidadBase: 350, unidad: "ml" },
  { grupo: "Grasas", alimento: "Bebida de avellana", cantidadBase: 250, unidad: "ml" },
  { grupo: "Grasas", alimento: "Bebida de avellana y arroz Hacendado", cantidadBase: 200, unidad: "ml" },
  { grupo: "Mixto (P+H)", alimento: "Legumbre cocida", cantidadBase: 100, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Legumbre en seco", cantidadBase: 30, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Pasta de legumbre", cantidadBase: 30, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Leche sin grasa", cantidadBase: 300, unidad: "ml" },
  { grupo: "Mixto (P+H)", alimento: "Leche desnatada +proteínas Hacendado", cantidadBase: 230, unidad: "ml" },
  { grupo: "Mixto (P+H)", alimento: "Leche baja en grasa", cantidadBase: 250, unidad: "ml" },
  { grupo: "Mixto (P+H)", alimento: "Leche semidesnatada +proteínas Hacendado", cantidadBase: 180, unidad: "ml" },
  { grupo: "Mixto (P+H)", alimento: "Kéfir sin grasa", cantidadBase: 250, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Yogurt griego sin grasa", cantidadBase: 170, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Yogurt natural (1 unidad)", cantidadBase: 125, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Yogures naturales desnatados 0% (2 unidades)", cantidadBase: 250, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Yogurt +proteínas chocolate o vainilla", cantidadBase: 120, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Yogurt alto en proteínas Pastoret", cantidadBase: 160, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Yogurt YoPro chocolate Danone", cantidadBase: 1, unidad: "ud" },
  { grupo: "Mixto (P+H)", alimento: "Yogurt mango sin azúcares añadidos Alpro", cantidadBase: 150, unidad: "g" },
  { grupo: "Mixto (P+H)", alimento: "Levadura de cerveza", cantidadBase: 30, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Leche entera", cantidadBase: 150, unidad: "ml" },
  { grupo: "Mixto (P+G)", alimento: "Bebida de soja sin azúcares añadidos", cantidadBase: 300, unidad: "ml" },
  { grupo: "Mixto (P+G)", alimento: "Yogurt de soja natural", cantidadBase: 200, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Kéfir natural", cantidadBase: 130, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Queso (curado, semicurado, cabra, mozzarella...)", cantidadBase: 30, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Mozzarella light o feta light", cantidadBase: 60, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Huevo (1 grande o 2 pequeños)", cantidadBase: 1, unidad: "ud" },
  { grupo: "Mixto (P+G)", alimento: "Carne roja grasa (cordero)", cantidadBase: 70, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Jamón serrano", cantidadBase: 50, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Pescado azul (salmón, sardina, caballa...)", cantidadBase: 65, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Salmón ahumado", cantidadBase: 60, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Anchoas en conserva", cantidadBase: 50, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Atún o sardinas en aceite (1 lata)", cantidadBase: 60, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Mejillones en escabeche (1 grande o 2 peq.)", cantidadBase: 1, unidad: "ud" },
  { grupo: "Mixto (P+G)", alimento: "Calamares en su tinta o salsa americana", cantidadBase: 1, unidad: "ud" },
  { grupo: "Mixto (P+G)", alimento: "Tempeh", cantidadBase: 55, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Tofu extra firme (menos de 115kcal/100g)", cantidadBase: 100, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Tofu silken (más de 115kcal/100g)", cantidadBase: 65, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Heura (bocados, picada, merluza)", cantidadBase: 70, unidad: "g" },
  { grupo: "Mixto (P+G)", alimento: "Heura (albóndigas, nuggets)", cantidadBase: 50, unidad: "g" },
];

const client = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN!,
});

const db = drizzle(client);

async function seed() {
  console.log("Seeding database with", staticFoods.length, "foods...");

  for (const food of staticFoods) {
    await db.insert(foodsTable).values({
      grupo: food.grupo,
      alimento: food.alimento,
      cantidadBase: food.cantidadBase,
      unidad: food.unidad,
    });
  }

  console.log("Done! Inserted", staticFoods.length, "foods.");
}

seed().catch(console.error);
